### ISSUE TITLE
LDAP Documentation

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot-docker-compose#23]
The section references to two variables but only one is documented

https://github.com/nautobot/nautobot-docker-compose/blob/main/docs/ldap.md#environment-controls

> There are **two environment variables** that will control the environment for the container.
>
> **Python Version**
>The version of Python used in the Dockerfile defaults to Python3.9

**Comment by jvanderaa** [comment]
I should get to this update soon.

**Comment by jdrew82** [comment]
This has been fixed with the poetry refactor.
