### ISSUE TITLE
bring up ports only on localhost

### ISSUE THREAD

**Issue by jonnjonzzn** [nautobot/nautobot-docker-compose#34]
I'm trying to bring up the system only listening on 127.0.0.1 so I can access via a reverse proxy front-end, there are multiple services on the server.  I am setting the ports section as follows:

    ports:
#     - "8443:8443"
       - "127.0.0.1:8080:8080"

But when I attempt to bring up with docker-compose up -d I get the following error:

Error response from daemon: driver failed programming external connectivity on endpoint nautobot-docker-compose-nautobot-1 (74bdbcc15abbe36edcb02a99a015754724688250dd6db734389892af83ca0b23): Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use

I can confirm there is nothing else on this port prior.  Wondering if someone could provide direction.  I was able to accomplish a similar setup with NetBox.  Thank y'all for what you do.

**Comment by jvanderaa** [comment]
What does the output of `ss -ltn` look like if a Linux host. The message is indicating that the binding is already in use.

**Comment by jonnjonzzn** [comment]
Sorry for delay and thank you for reply.

[15:42:17][root@assetmgmtdev1][/data/docker/nautobot-docker-compose]# ss -ltn
State              Recv-Q             Send-Q                         Local Address:Port                         Peer Address:Port            Process            
LISTEN             0                  128                                127.0.0.1:8000                              0.0.0.0:*                                  
LISTEN             0                  5                                    0.0.0.0:5666                              0.0.0.0:*                                  
LISTEN             0                  128                                  0.0.0.0:9090                              0.0.0.0:*                                  
LISTEN             0                  128                                  0.0.0.0:111                               0.0.0.0:*                                  
LISTEN             0                  128                                  0.0.0.0:80                                0.0.0.0:*                                  
LISTEN             0                  128                                  0.0.0.0:22                                0.0.0.0:*                                  
LISTEN             0                  128                                  0.0.0.0:443                               0.0.0.0:*

**Comment by jonnjonzzn** [comment]
So I just decided to try another port and it came up fine.  I'm sure there is a logical reason why was failing on 8080 but I'm going to move on with a working solution.  Thank you and sorry for the noise.

This was fine...

    ports:
#      - "8443:8443"
      - "127.0.0.1:8001:8080"

**Comment by jvanderaa** [comment]
All good - thanks for the note back. It should have come up on 8080 there. Unless it was taking 8000 for some reason.
