### ISSUE TITLE
Update LDAP Docs

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-docker-compose#37]
I believe the LDAP requirements are baked in to the Nautobot container now, worth a double check but could reduce the code here.

**Comment by jvanderaa** [comment]
Such that one doesn't need to rebuild the container for LDAP?

**Comment by nniehoff** [comment]
That is the idea yes...  I don't have a PR as I don't have time yet...

**Comment by scetron** [comment]
Something related is that in the `nautobot_config.py.ldap` the `nautobot-device-onboarding` is enabled in plugins but is not installed into the container. Probably needs to be removed from `PLUGINS` in the config.

**Comment by jvanderaa** [comment]
@scetron you want this one?

**Comment by scetron** [comment]
Yes, I can take this one

**Comment by jvanderaa** [comment]
Sounds good @scetron

**Comment by terafirmanz** [comment]
Does this mean I should not submit an issue for the ldap compose file?

Currently, the ldap file has the database service named postgres but the main compose file calls it "db" so using the default env file will fail to start.

**Comment by jdrew82** [comment]
This has been resolved.
