### ISSUE TITLE
Update Docs for Docker Compose New Install Method

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-docker-compose#40]
The new instructions for Docker Compose puts compose as an option of the Docker executable. These docs should be updated to reflect this.

**Comment by itheodoridis** [comment]
I believe this is dependent on the docker compose version, not on docker executable directly. So the version should be mentioned but perhaps also a link to an installation how-to for docker compose. The Digital Ocean guides are great for this, or maybe one should be written from scratch or adapted.

**Comment by jdrew82** [comment]
This has been corrected so closing.
