### ISSUE TITLE
Default configuration does not mount `config/nautobot_config.py`

### ISSUE THREAD

**Issue by foxx** [nautobot/nautobot-docker-compose#41]
This repo is a good starting point, but it might be a bit confusing for newcomers as the `config/nautobot_config.py` is not mounted by default and thus does not apply any of the customisations specified by the user.

Presumably `docker-compose.yml` should have a `volumes` mount for `./config/nautobot_config.py` into `/opt/nautobot/nautobot_config.py`, e.g.;

```
    volumes:
      - "./config/nautobot_config.py:/opt/nautobot/nautobot_config.py:ro"
 ```

Let me know if you'd take a PR for this and I'll happily fix, thanks.

**Comment by foxx** [comment]
Ahh nevermind, just realised this is handled in the `Dockerfile` for plugins.

**Comment by pentiumoverdrive** [comment]
Can you elaborate?  Can't figure out how this is supposed to work as intended.
Thx
