### ISSUE TITLE
There are significant differences between the various docker-compose files - inclusion of a separate celery beat service

### ISSUE THREAD

**Issue by itheodoridis** [nautobot/nautobot-docker-compose#46]
Between the simple docker-compose.yml, the docker-compose.ldap.yml and the docker-compose.override.yml.example there are significant differences. For example the inclusion of a seperate celery beat service in docker-compose.yml which is not included in the other two. Also the dependencies for each service, and the test arguments for the celery worker.
Especially the need for inclusion of a separate celery beat service should be addressed and configuration settings should be reviewed. So that one common view/direction is produced for all cases (ldap/plugins/etc) for the docker-compose based nautobot deployment.

**Comment by itheodoridis** [comment]
About the celery beat, while digging I just noticed there's a pull request about it. Also review and tests have been completed. Maybe I am not so experienced in this kind of thing but what's keeping it from being merged?
https://github.com/nautobot/nautobot-docker-compose/pull/29/files

**Comment by jvanderaa** [comment]
Updates made to get up to the latest. Need to also figure out how to appropriately keep the library up to date with less effort yet.

**Comment by jvanderaa** [comment]
Hopefully #29 will handle this.

**Comment by jdrew82** [comment]
This has been addressed so closing.
