### ISSUE TITLE
Uploaded images do not persist across restarts

### ISSUE THREAD

**Issue by apanagio** [nautobot/nautobot-docker-compose#51]
If you stop and restart nautobot instance, you cannot view the uploaded images
### Way to reproduce
- Start nautobot using docker-compose
- Upload an image to a site
- Restart nautobot
- Notice the previously uploaded files are missing 

### Explanation
If I understand correctly this happens because the uploaded images are stored in the file system within the container and the filesystem is purged when the container stops

### Proposed Fix
Mount a volume from the host system to store uploaded files

**Comment by jvanderaa** [comment]
@apanagio do you have a proposed standard of where to mount the volumes back to on the host? I feel like that may be something that we can add on via documentation unless we have a standard to adhere to?

**Comment by EdificomSA** [comment]
I did set
```yaml
    volumes:
    - nautobot-media-files:/opt/nautobot/media
```
in `docker-compose.override.yml` for the "main" nautobot service

**Comment by rlad78** [comment]
@EdificomSA how did you set up your permissions so that the `nautobot` user can write to that volume? I'm getting the following while trying to stand up Nautobot v1.6.2:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/runner/runner.py", line 117, in settings_callback
    initializer(
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/cli.py", line 123, in _configure_settings
    os.makedirs(os.path.join(settings.MEDIA_ROOT, "devicetype-images"))
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/nautobot/media/devicetype-images'
```

**Comment by EdificomSA** [comment]
Yeah you might need to chown the folder in the named volume, look at :
https://github.com/docker/compose/issues/3270#issuecomment-1245819741
