### ISSUE TITLE
Docker swarm

### ISSUE THREAD

**Issue by borgermeister** [nautobot/nautobot-docker-compose#53]
Trying to get the compose file to work on Docker Swarm but all containers exits with error code 137. Only Redis and Postgres container is working.

**Comment by jvanderaa** [comment]
What is error code 137? Is that something from Docker itself?

**Comment by jvanderaa** [comment]
It looks like Error 137 is related to not enough memory. How is Swarm handling the memory allocations for the containers?

**Comment by jvanderaa** [comment]
https://www.containiq.com/post/exit-code-137

**Comment by jdrew82** [comment]
This appears to be a resource issue related to the Docker Swarm platform so I don't believe is anything that we need to address. Closing.
