### ISSUE TITLE
Don't reference MariaDB in Mysql example

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-docker-compose#55]
Since Nautobot does not officially support MariaDB, we should not recommend it in the nautobot-docker-compose/docker-compose.mysql.yaml file.

        Although we cannot officially support MariaDB at this time, we did do a little research to address this issue for you.

I confirmed that if you explicitly `pip install django-mptt==0.11.0` for your Nautobot installation, that this issue is alleviated. Note, however, that `pip` will complain about the version conflict with Nautobot's requirements, but it's just a warning that can be safely ignored in this case.

Since there are no other dependencies or conflicts with `django-mptt`, this should be fine for now in your deployment. Also, we do plan to get rid of this library in our v2.0.0 release, so this issue will also no longer be a concern.

I'll be closing this issue. Thanks for reporting it!

_Originally posted by @jathanism in https://github.com/nautobot/nautobot/issues/1724#issuecomment-1132058843_

**Comment by jvanderaa** [comment]
Interesting that this worked on the example sent.
