### ISSUE TITLE
NAUTOBOT_CACHEOPS_REDIS error in example files

### ISSUE THREAD

**Issue by BoudewijnSwen** [nautobot/nautobot-docker-compose#62]
in https://github.com/nautobot/nautobot-docker-compose/blob/main/local.env.example row 24:
`NAUTOBOT_CACHEOPS_REDIS=redis://:decinablesprewad@redis:6379/1`

There is an extra : in there after `redis://`

Same thing in https://github.com/nautobot/nautobot-docker-compose/blob/main/config/nautobot_config.py.ldap row 61.
`CACHEOPS_REDIS = os.getenv("NAUTOBOT_CACHEOPS_REDIS", f"{redis_protocol}://:{cache_ops_pwd}@{cache_ops_host}:{cache_ops_port}/1")`

This caused al sorts of weird behavior in my deployment, after I removed the redundant semi colon it all worked smooth.

**Comment by jdrew82** [comment]
This is no longer relevant.
