### ISSUE TITLE
rq import problems with release 1.6

### ISSUE THREAD

**Issue by nerrehmit** [nautobot/nautobot-docker-compose#63]
Just a quick documentation of an issue I had today while using the docker-compose setup to spin up a Nautobot 1.6 instance for testing.

https://github.com/nautobot/nautobot-docker-compose/blob/main/config/nautobot_config.py.ldap#L353 imports the `ColorizingStreamHandler` class from `rq.utils.`

But since `django-rq` was bumped from 2.5.1 to 2.8.1 for the Nautobot 1.6 release [here](https://github.com/nautobot/nautobot/commit/9722b0880ff0407cdbae2c43d1c89f5482336f6e) the `rq` dependency has automatically been updated to >=1.15.1.

`rq` moved the class `ColorizingStreamHandler` from the `utils.py` to `logutils.py` [here](https://github.com/rq/rq/commit/36f5c88ca21ff30fb799e7d10b2f7b9bef4e585a#diff-131ce6502fe39f72674a7d588e39152a3d8eea79d8ca3483b951f6957d0ce8f1), unfortunately without mentioning it in the 1.14.0 release notes.

To get back to a working docker setup with Nautobot 1.6 you have to change the import statement in the LDAP config like I did in my fork [here](https://github.com/nautobot/nautobot-docker-compose/compare/main...nerrehmit:nautobot-docker-compose:nerrehmit-rq-colorizing-import).

**Comment by JonathanNathanson** [comment]
I find that this issue happens with almost any version of Nautobot I've tried to install when I am using the docs to install plugins with a docker compose setup.  The fix noted is very helpful, thank you.

**Comment by jdrew82** [comment]
RQ is no longer supported by Nautobot and has been replaced by Celery. Any mentions of RQ should be removed and replaced with Celery.

**Comment by jdrew82** [comment]
This is no longer relevant, closing.
