### ISSUE TITLE
Changes with 2.X

### ISSUE THREAD

**Issue by bile0026** [nautobot/nautobot-docker-compose#64]
It seems that now, after the 2.X release train is live buliding custom containers installs the latest version of nautobot and any plugins (apps) by default. This requires having to set versions manually in the requrements.txt file. Should this be using Poetry instead to manage these dependencies since that's our standard for other buildl environments? 

This results in the Nautobot 2.X train being installed in the containers at build-time, even if NAUTOBOT_VERSION is set to a 1.X version. 

This also breaks the database tables once the 2.X migrations run and a database backup is required to be restored.

This does not seem like desirable behavior to me.

**Comment by jdrew82** [comment]
IMO we should refactor this project to use poetry for all dependency management. It would easily resolve this issue and more closely align with how we already deploy Nautobot typically. I'll work on getting a PR in for this.

**Comment by jdrew82** [comment]
This has been completed so closing.
