### ISSUE TITLE
nautobot-server post_upgrade: error: unrecognized arguments: --no-invalidate-all

### ISSUE THREAD

**Issue by skumarmallampeta** [nautobot/nautobot-docker-compose#65]
Hi Admin,

I have been running nautobot using docker which was working fine until I recently tried to install a new plugin and then perform a post_upgrade but it is failing due to the below error which I think is similar to the one mentioned here https://github.com/nautobot/nautobot/pull/4555 . Can you please assist on how to resolve this issue as my Nautobot is currently down

nautobot_1         |                                     [--no-refresh-content-type-cache]
nautobot_1         |                                     [--no-refresh-dynamic-group-member-caches]
nautobot_1         | nautobot-server post_upgrade: error: unrecognized arguments: --no-invalidate-all
nautobot_1         | ⏳ Waiting on DB... (3s / 30s)
nautobot-worker_1  | Grafana ChatOps integration is not available.
nautobot-worker_1  | NoneType: None
nautobot-worker_1  | 20:33:04.044 ERROR   nautobot.core.apps :
nautobot-worker_1  |   Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
nautobot-worker_1  | usage: nautobot-server post_upgrade [-h] [--version] [-v {0,1,2,3}]
nautobot-worker_1  |                                     [--settings SETTINGS]
nautobot-worker_1  |                                     [--pythonpath PYTHONPATH] [--traceback]
nautobot-worker_1  |                                     [--no-color] [--force-color]
nautobot-worker_1  |                                     [--skip-checks] [--no-build-ui]
nautobot-worker_1  |                                     [--no-clearsessions] [--no-collectstatic]
nautobot-worker_1  |                                     [--no-migrate]
nautobot-worker_1  |                                     [--no-remove-stale-contenttypes]
nautobot-worker_1  |                                     [--no-trace-paths]
nautobot-worker_1  |                                     [--no-send-installation-metrics]
nautobot-worker_1  |                                     [--no-refresh-content-type-cache]
nautobot-worker_1  |                                     [--no-refresh-dynamic-group-member-caches]
nautobot-worker_1  | nautobot-server post_upgrade: error: unrecognized arguments: --no-invalidate-all
nautobot-worker_1  | ⏳ Waiting on DB... (6s / 30s)

**Comment by glennmatthews** [comment]
`--no-invalidate-all` was removed in Nautobot 2.0. Did the plugin installation result in inadvertently upgrading the version of Nautobot in the container?

**Comment by skumarmallampeta** [comment]
closing the issue as I had to specify 1.6 version in docker yaml for nautobot and its plugins and stopped noticing it
