### ISSUE TITLE
docker.compose never ends

### ISSUE THREAD

**Issue by moseisleydk** [nautobot/nautobot-docker-compose#67]
I have followed the description and I can get the UI etc.

But the "docker-compose up" command never ends, I stops:

`root@nautobot01:/opt/nautobot/nautobot-docker-compose# docker-compose up
Starting nautobot-docker-compose_nautobot_1 ... done
Starting nautobot-docker-compose_db_1       ... done
Starting nautobot-docker-compose_redis_1    ... done
Starting nautobot-docker-compose_celery_worker_1 ... done
Starting nautobot-docker-compose_celery_beat_1   ... done
Attaching to nautobot-docker-compose_db_1, nautobot-docker-compose_nautobot_1, nautobot-docker-compose_redis_1, nautobot-docker-compose_celery_worker_1, nautobot-docker-compose_celery_beat_1
db_1             | 
db_1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1             | 
db_1             | 2023-12-14 12:39:02.781 UTC [1] LOG:  starting PostgreSQL 13.13 (Debian 13.13-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db_1             | 2023-12-14 12:39:02.781 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1             | 2023-12-14 12:39:02.781 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1             | 2023-12-14 12:39:02.787 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1             | 2023-12-14 12:39:02.795 UTC [26] LOG:  database system was shut down at 2023-12-14 12:38:56 UTC
db_1             | 2023-12-14 12:39:02.803 UTC [1] LOG:  database system is ready to accept connections
redis_1          | 1:C 14 Dec 2023 12:39:02.825 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:C 14 Dec 2023 12:39:02.825 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 14 Dec 2023 12:39:02.825 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 14 Dec 2023 12:39:02.825 * Configuration loaded
redis_1          | 1:M 14 Dec 2023 12:39:02.825 * monotonic clock: POSIX clock_gettime
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Running mode=standalone, port=6379.
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Server initialized
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Reading RDB base file on AOF loading...
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Loading RDB produced by version 7.2.3
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * RDB age 470 seconds
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * RDB memory usage when created 0.83 Mb
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * RDB is base AOF
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.000 seconds
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * DB loaded from append only file: 0.000 seconds
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
redis_1          | 1:M 14 Dec 2023 12:39:02.826 * Ready to accept connections tcp
nautobot_1       | Performing database migrations...
nautobot_1       | Operations to perform:
nautobot_1       |   Apply all migrations: admin, auth, circuits, contenttypes, database, dcim, django_celery_beat, django_rq, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization
nautobot_1       | Running migrations:
nautobot_1       |   No migrations to apply.
celery_beat_1    | celery beat v5.2.7 (dawn-chorus) is starting.
nautobot_1       | 
nautobot_1       | Generating cable paths...
nautobot_1       | Found no missing circuit termination paths; skipping
nautobot_1       | Found no missing console port paths; skipping
nautobot_1       | Found no missing console server port paths; skipping
nautobot_1       | Found no missing interface paths; skipping
nautobot_1       | Found no missing power feed paths; skipping
nautobot_1       | Found no missing power outlet paths; skipping
nautobot_1       | Found no missing power port paths; skipping
nautobot_1       | Finished.
nautobot_1       | 
nautobot_1       | Collecting static files...
celery_worker_1  |  
celery_worker_1  |  -------------- celery@2c9d9ae6e123 v5.2.7 (dawn-chorus)
celery_worker_1  | --- ***** ----- 
celery_worker_1  | -- ******* ---- Linux-5.15.0-25-generic-x86_64-with-glibc2.31 2023-12-14 12:39:10
celery_worker_1  | - *** --- * --- 
celery_worker_1  | - ** ---------- [config]
celery_worker_1  | - ** ---------- .> app:         nautobot:0x7f6e161d0610
celery_worker_1  | - ** ---------- .> transport:   redis://:**@redis:6379/0
celery_worker_1  | - ** ---------- .> results:     redis://:**@redis:6379/0
celery_worker_1  | - *** --- * --- .> concurrency: 2 (prefork)
celery_worker_1  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery_worker_1  | --- ***** ----- 
celery_worker_1  |  -------------- [queues]
celery_worker_1  |                 .> default          exchange=default(direct) key=default
celery_worker_1  |                 
celery_worker_1  | 
nautobot_1       | 
nautobot_1       | 0 static files copied to '/opt/nautobot/static', 720 unmodified.
nautobot_1       | 
nautobot_1       | Removing stale content types...
nautobot_1       | 
nautobot_1       | Removing expired sessions...
nautobot_1       | 
celery_beat_1    | __    -    ... __   -        _
celery_beat_1    | LocalTime -> 2023-12-14 12:39:10
celery_beat_1    | Configuration ->
celery_beat_1    |     . broker -> redis://:**@redis:6379/0
celery_beat_1    |     . loader -> celery.loaders.app.AppLoader
celery_beat_1    |     . scheduler -> nautobot.core.celery.schedulers.NautobotDatabaseScheduler
celery_beat_1    | 
celery_beat_1    |     . logfile -> [stderr]@%WARNING
celery_beat_1    |     . maxinterval -> 5.00 seconds (5s)
nautobot_1       | ⏳ Running initial systems check...
nautobot_1       | System check identified some issues:
nautobot_1       | 
nautobot_1       | WARNINGS:
nautobot_1       | ?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
nautobot_1       | ?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
nautobot_1       | ?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
nautobot_1       | ?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
nautobot_1       | 
nautobot_1       | System check identified 4 issues (0 silenced).
nautobot_1       | 💡 Superuser Username: admin, E-Mail: admin@example.com
nautobot_1       | [uWSGI] getting INI configuration from /opt/nautobot/uwsgi.ini
nautobot_1       | [uwsgi-static] added mapping for /static => /opt/nautobot/static
nautobot_1       | *** Starting uWSGI 2.0.21 (64bit) on [Thu Dec 14 12:39:31 2023] ***
nautobot_1       | compiled with version: 10.2.1 20210110 on 20 February 2023 06:12:35
nautobot_1       | os: Linux-5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022
nautobot_1       | nodename: 6589ea9ea190
nautobot_1       | machine: x86_64
nautobot_1       | clock source: unix
nautobot_1       | detected number of CPU cores: 2
nautobot_1       | current working directory: /opt/nautobot
nautobot_1       | detected binary path: /usr/local/bin/python3.9
nautobot_1       | !!! no internal routing support, rebuild with pcre support !!!
nautobot_1       | your memory page size is 4096 bytes
nautobot_1       | detected max file descriptor number: 1048576
nautobot_1       | building mime-types dictionary from file /etc/mime.types...1476 entry found
nautobot_1       | lock engine: pthread robust mutexes
nautobot_1       | thunder lock: disabled (you can enable it with --thunder-lock)
nautobot_1       | uWSGI http bound on 0.0.0.0:8080 fd 10
nautobot_1       | uWSGI http bound on 0.0.0.0:8443 fd 11
nautobot_1       | uwsgi socket 0 bound to TCP address 127.0.0.1:34903 (port auto-assigned) fd 9
nautobot_1       | Python version: 3.9.16 (main, Feb  9 2023, 05:40:23)  [GCC 10.2.1 20210110]
nautobot_1       | --- Python VM already initialized ---
nautobot_1       | Python main interpreter initialized at 0x56152133cb90
nautobot_1       | python threads support enabled
nautobot_1       | your server socket listen backlog is limited to 128 connections
nautobot_1       | your mercy for graceful operations on workers is 60 seconds
nautobot_1       | mapped 291680 bytes (284 KB) for 3 cores
nautobot_1       | *** Operational MODE: preforking ***
nautobot_1       | 12:39:31.136 INFO    nautobot :
nautobot_1       |   Nautobot initialized!
nautobot_1       | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x56152133cb90 pid: 1 (default app)
nautobot_1       | spawned uWSGI master process (pid: 1)
nautobot_1       | spawned uWSGI worker 1 (pid: 79, cores: 1)
nautobot_1       | spawned uWSGI worker 2 (pid: 80, cores: 1)
nautobot_1       | spawned uWSGI worker 3 (pid: 81, cores: 1)
nautobot_1       | 12:39:31.164 INFO    nautobot.core.wsgi :
nautobot_1       |   Closing existing DB and cache connections on worker 1 after uWSGI forked ...
nautobot_1       | 12:39:31.169 INFO    nautobot.core.wsgi :
nautobot_1       |   Closing existing DB and cache connections on worker 2 after uWSGI forked ...
nautobot_1       | spawned uWSGI http 1 (pid: 82)
nautobot_1       | 12:39:31.176 INFO    nautobot.core.wsgi :
nautobot_1       |   Closing existing DB and cache connections on worker 3 after uWSGI forked ...
`

If I break it, the system (of cause) dies.

**Comment by matt-edu** [comment]
Try: docker-compose up -d

**Comment by jdrew82** [comment]
This is no longer relevant.
