### ISSUE TITLE
tasks.py:254: SyntaxWarning: invalid escape sequence '\$'

### ISSUE THREAD

**Issue by jpedersen01** [nautobot/nautobot-docker-compose#80]
When doing the invoke start, I see the following errors and the celery instances die and eventually the nautobot instance dies.
/home/james/nautobot/nautobot-docker-compose/tasks.py:254: SyntaxWarning: invalid escape sequence '\$'
  export_cmd = 'exec db sh -c "mysqldump -u \${NAUTOBOT_DB_USER} –p \${NAUTOBOT_DB_PASSWORD} \${NAUTOBOT_DB_NAME} nautobot > /tmp/nautobot.sql"'  # noqa: W605 pylint: disable=anomalous-backslash-in-string
/home/james/nautobot/nautobot-docker-compose/tasks.py:257: SyntaxWarning: invalid escape sequence '\$'
  export_cmd = 'exec db sh -c "pg_dump -h localhost -d \${NAUTOBOT_DB_NAME} -U \${NAUTOBOT_DB_USER} > /tmp/nautobot.sql"'  # noqa: W605 pylint: disable=anomalous-backslash-in-string
/home/james/nautobot/nautobot-docker-compose/tasks.py:276: SyntaxWarning: invalid escape sequence '\$'
  import_cmd = 'exec db sh -c "mysql -u \${NAUTOBOT_DB_USER} –p \${NAUTOBOT_DB_PASSWORD} < /tmp/nautobot.sql"'  # noqa: W605 pylint: disable=anomalous-backslash-in-string
/home/james/nautobot/nautobot-docker-compose/tasks.py:279: SyntaxWarning: invalid escape sequence '\$'
  import_cmd = 'exec db sh -c "psql -h localhost -U \${NAUTOBOT_DB_USER} < /tmp/nautobot.sql"'  # noqa: W605 pylint: disable=anomalous-backslash-in-string
Starting Nautobot in detached mode...
Running docker compose command "up --detach"
 Container nautobot_docker_compose-db-1  Creating
 Container nautobot_docker_compose-redis-1  Creating
 Container nautobot_docker_compose-db-1  Created
 Container nautobot_docker_compose-redis-1  Created
 Container nautobot_docker_compose-nautobot-1  Creating
 Container nautobot_docker_compose-nautobot-1  Created
 Container nautobot_docker_compose-celery_worker-1  Creating
 Container nautobot_docker_compose-celery_beat-1  Creating
 Container nautobot_docker_compose-celery_beat-1  Created
 Container nautobot_docker_compose-celery_worker-1  Created
 Container nautobot_docker_compose-db-1  Starting
 Container nautobot_docker_compose-redis-1  Starting
 Container nautobot_docker_compose-redis-1  Started
 Container nautobot_docker_compose-db-1  Started
 Container nautobot_docker_compose-nautobot-1  Starting
 Container nautobot_docker_compose-nautobot-1  Started
 Container nautobot_docker_compose-celery_beat-1  Starting
 Container nautobot_docker_compose-celery_worker-1  Starting
 Container nautobot_docker_compose-celery_worker-1  Started
 Container nautobot_docker_compose-celery_beat-1  Started

Celery log:
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "db" (172.24.0.3), port 5432 failed: FATAL:  password authentication failed for user "nautobot"

What am I missing?

**Comment by jdrew82** [comment]
That error is saying that you don't have the `NAUTOBOT_DB_PASSWORD` environment variable defined. You need to ensure that you have the creds.env file in place that contains that environment variable. I'd suggest redoing the [Getting Started](https://github.com/nautobot/nautobot-docker-compose/blob/main/README.md#getting-started) steps as step 4 is to copy the creds.env and local.env from the example files.
