### ISSUE TITLE
Device Onboarding Dependency Confusion

### ISSUE THREAD

**Issue by alhogan** [nautobot/nautobot-docker-compose#81]
The second pyproject.toml file hidden in `plugins/example_plugin` causes headaches if you happen to add the device onboarding app as a dependency in the pyproject.toml at the root level. Is the example plugin really needed or could we remove the device onboarding depency so prevent the potential conflict. Even loosing up the version requirement could help.

**Comment by jdrew82** [comment]
I think we're best to just comment out the example plugin from the Dockerfile and the pyproject.toml. It's just meant there as an example and not intended for actual usage.
